/**
 * 12 个种子词 — src/shared/consts/seeds.ts
 * 来源：统编教材三上第一单元（CLAUDE.md §5）
 * 字段含义见 @shared/types SeedWord
 */

import type { SeedWord } from '@shared/types';

export const SEED_WORDS: readonly SeedWord[] = [
  {
    id: 'seed-01',
    word: '凌乱',
    sceneIcon: '🍂',
    source: '《铺满金色巴掌的水泥道》',
    scene: '环境·秋天',
    reason: '画面感',
    reasonHint: '秋风吹过落叶，七零八落',
    order: 1,
  },
  {
    id: 'seed-02',
    word: '潮湿',
    sceneIcon: '🌧️',
    source: '《铺满金色巴掌的水泥道》',
    scene: '环境·雨后',
    reason: '画面感',
    reasonHint: '雨后地面湿漉漉的样子',
    order: 2,
  },
  {
    id: 'seed-03',
    word: '熨帖',
    sceneIcon: '👕',
    source: '《铺满金色巴掌的水泥道》',
    scene: '动作·整理',
    reason: '动词精准',
    reasonHint: '用"熨"这个动作，比"贴"更有画面',
    order: 3,
  },
  {
    id: 'seed-04',
    word: '憧憬',
    sceneIcon: '😊',
    source: '《不懂就要问》',
    scene: '心情·期待',
    reason: '画面感',
    reasonHint: '眼睛发亮望着远方的样子',
    order: 4,
  },
  {
    id: 'seed-05',
    word: '私塾',
    sceneIcon: '📜',
    source: '《不懂就要问》',
    scene: '场景·古时',
    reason: '画面感',
    reasonHint: '古代学堂的样子',
    order: 5,
  },
  {
    id: 'seed-06',
    word: '鸦雀无声',
    sceneIcon: '🤫',
    source: '《不懂就要问》',
    scene: '声音·安静',
    reason: '声音词',
    reasonHint: '用两个动物名代替"很安静"，更有画面',
    order: 6,
  },
  {
    id: 'seed-07',
    word: '摇晃',
    sceneIcon: '🌸',
    source: '《花的学校》',
    scene: '动作·自然',
    reason: '拟人',
    reasonHint: '把花当成会跳舞的人来写',
    order: 7,
  },
  {
    id: 'seed-08',
    word: '狂欢',
    sceneIcon: '🎉',
    source: '《花的学校》',
    scene: '心情·快乐',
    reason: '拟人',
    reasonHint: '把花当成一群过节的孩子',
    order: 8,
  },
  {
    id: 'seed-09',
    word: '叮咛',
    sceneIcon: '👵',
    source: '课外·描写长辈',
    scene: '声音·关怀',
    reason: '声音词',
    reasonHint: '奶奶一遍遍嘱咐的声音',
    order: 9,
  },
  {
    id: 'seed-10',
    word: '绽放',
    sceneIcon: '🌺',
    source: '《花的学校》',
    scene: '动作·花开',
    reason: '比喻',
    reasonHint: '把花开比作笑容绽放',
    order: 10,
  },
  {
    id: 'seed-11',
    word: '好奇',
    sceneIcon: '👀',
    source: '《不懂就要问》',
    scene: '心情·疑问',
    reason: '对比',
    reasonHint: '和"无所谓"对比，突出爱思考',
    order: 11,
  },
  {
    id: 'seed-12',
    word: '出奇',
    sceneIcon: '✨',
    source: '课外·描写惊喜',
    scene: '心情·意外',
    reason: '动词精准',
    reasonHint: '比"很特别"更有力量',
    order: 12,
  },
] as const;
